### PR TITLE
Vendor

### PR DESCRIPTION
**Pull request by grb43**
This PR is to use Go vendering in place of Godeps. Vendering greatly simplifies building .rpm packages.
The modified code builds properly with 'go build', but I haven't testing the debian and cross-compile builds.

### CODE REVIEW

**Comment by Zillode** [comment]
Thanks for your PR, I'm looking into this

**Comment by Zillode** [comment]
Thanks for your contribution!

**Comment by polyzen** [comment]
godep does vendoring:
https://github.com/tools/godep#how-to-use-godep-with-a-new-project

**Comment by AudriusButkevicius** [comment]
Sure, so does many other tools, what's your point?

**Comment by polyzen** [comment]
I don't see why godep was dropped, then.

**Comment by AudriusButkevicius** [comment]
Because since Go 1.something, Go provides it's own support for vendoring. 
Go itself does not support dependency management yet, but godep is quite bad it it too, and from experience on syncthing, gvt is much better at it. It seems this PR converts to use that instead, which makes it inline with syncthing.

**Comment by polyzen** [comment]
Fantastic! Thank you for enlightening me.

**Pull request merged**
